//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrickController2.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TranslationResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TranslationResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("BrickController2.Resources.TranslationResources", typeof(TranslationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        internal static string AddControllerEvents {
            get {
                return ResourceManager.GetString("AddControllerEvents", resourceCulture);
            }
        }
        
        internal static string AddControllerProfiles {
            get {
                return ResourceManager.GetString("AddControllerProfiles", resourceCulture);
            }
        }
        
        internal static string AddControlPoints {
            get {
                return ResourceManager.GetString("AddControlPoints", resourceCulture);
            }
        }
        
        internal static string AddCreations {
            get {
                return ResourceManager.GetString("AddCreations", resourceCulture);
            }
        }
        
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        internal static string AddSequences {
            get {
                return ResourceManager.GetString("AddSequences", resourceCulture);
            }
        }
        
        internal static string AdvancedSettings {
            get {
                return ResourceManager.GetString("AdvancedSettings", resourceCulture);
            }
        }
        
        internal static string AreYouSureToDeleteControllerAction {
            get {
                return ResourceManager.GetString("AreYouSureToDeleteControllerAction", resourceCulture);
            }
        }
        
        internal static string AreYouSureToDeleteControllerEvent {
            get {
                return ResourceManager.GetString("AreYouSureToDeleteControllerEvent", resourceCulture);
            }
        }
        
        internal static string AreYouSureToDeleteControlPoint {
            get {
                return ResourceManager.GetString("AreYouSureToDeleteControlPoint", resourceCulture);
            }
        }
        
        internal static string AreYouSureToDeleteCreation {
            get {
                return ResourceManager.GetString("AreYouSureToDeleteCreation", resourceCulture);
            }
        }
        
        internal static string AreYouSureToDeleteDevice {
            get {
                return ResourceManager.GetString("AreYouSureToDeleteDevice", resourceCulture);
            }
        }
        
        internal static string AreYouSureToDeleteProfile {
            get {
                return ResourceManager.GetString("AreYouSureToDeleteProfile", resourceCulture);
            }
        }
        
        internal static string AreYouSureToDeleteSequence {
            get {
                return ResourceManager.GetString("AreYouSureToDeleteSequence", resourceCulture);
            }
        }
        
        internal static string AreYouSureToDeleteThisControllerAcrion {
            get {
                return ResourceManager.GetString("AreYouSureToDeleteThisControllerAcrion", resourceCulture);
            }
        }
        
        internal static string AutoCalibrate {
            get {
                return ResourceManager.GetString("AutoCalibrate", resourceCulture);
            }
        }
        
        internal static string AxisCharacteristic {
            get {
                return ResourceManager.GetString("AxisCharacteristic", resourceCulture);
            }
        }
        
        internal static string AxisDeadZone {
            get {
                return ResourceManager.GetString("AxisDeadZone", resourceCulture);
            }
        }
        
        internal static string BaseAngle {
            get {
                return ResourceManager.GetString("BaseAngle", resourceCulture);
            }
        }
        
        internal static string Battery {
            get {
                return ResourceManager.GetString("Battery", resourceCulture);
            }
        }
        
        internal static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        internal static string BluetoothDevicesWillNOTBeAvailable {
            get {
                return ResourceManager.GetString("BluetoothDevicesWillNOTBeAvailable", resourceCulture);
            }
        }
        
        internal static string BluetoothIsTurnedOff {
            get {
                return ResourceManager.GetString("BluetoothIsTurnedOff", resourceCulture);
            }
        }
        
        internal static string ButtonType {
            get {
                return ResourceManager.GetString("ButtonType", resourceCulture);
            }
        }
        
        internal static string BuWizz2OutputLevel {
            get {
                return ResourceManager.GetString("BuWizz2OutputLevel", resourceCulture);
            }
        }
        
        internal static string BuWizzOutputLevel {
            get {
                return ResourceManager.GetString("BuWizzOutputLevel", resourceCulture);
            }
        }
        
        internal static string Calibrating {
            get {
                return ResourceManager.GetString("Calibrating", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string ChannelSetup {
            get {
                return ResourceManager.GetString("ChannelSetup", resourceCulture);
            }
        }
        
        internal static string ChannelType {
            get {
                return ResourceManager.GetString("ChannelType", resourceCulture);
            }
        }
        
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        internal static string Connecting {
            get {
                return ResourceManager.GetString("Connecting", resourceCulture);
            }
        }
        
        internal static string Controller {
            get {
                return ResourceManager.GetString("Controller", resourceCulture);
            }
        }
        
        internal static string ControllerAction {
            get {
                return ResourceManager.GetString("ControllerAction", resourceCulture);
            }
        }
        
        internal static string ControllerProfile {
            get {
                return ResourceManager.GetString("ControllerProfile", resourceCulture);
            }
        }
        
        internal static string ControllerTester {
            get {
                return ResourceManager.GetString("ControllerTester", resourceCulture);
            }
        }
        
        internal static string ControlPoint {
            get {
                return ResourceManager.GetString("ControlPoint", resourceCulture);
            }
        }
        
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        internal static string CopyControllerProfile {
            get {
                return ResourceManager.GetString("CopyControllerProfile", resourceCulture);
            }
        }
        
        internal static string Copying {
            get {
                return ResourceManager.GetString("Copying", resourceCulture);
            }
        }            
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        internal static string Creating {
            get {
                return ResourceManager.GetString("Creating", resourceCulture);
            }
        }
        
        internal static string Creation {
            get {
                return ResourceManager.GetString("Creation", resourceCulture);
            }
        }
        
        internal static string CreationName {
            get {
                return ResourceManager.GetString("CreationName", resourceCulture);
            }
        }
        
        internal static string CreationNameCanNotBeEmpty {
            get {
                return ResourceManager.GetString("CreationNameCanNotBeEmpty", resourceCulture);
            }
        }
        
        internal static string Creations {
            get {
                return ResourceManager.GetString("Creations", resourceCulture);
            }
        }
        
        internal static string DefaultProfile {
            get {
                return ResourceManager.GetString("DefaultProfile", resourceCulture);
            }
        }
        
        internal static string Deleting {
            get {
                return ResourceManager.GetString("Deleting", resourceCulture);
            }
        }
        
        internal static string Device {
            get {
                return ResourceManager.GetString("Device", resourceCulture);
            }
        }
        
        internal static string DeviceName {
            get {
                return ResourceManager.GetString("DeviceName", resourceCulture);
            }
        }
        
        internal static string DeviceNameCanNotBeEmpty {
            get {
                return ResourceManager.GetString("DeviceNameCanNotBeEmpty", resourceCulture);
            }
        }
        
        internal static string Devices {
            get {
                return ResourceManager.GetString("Devices", resourceCulture);
            }
        }
        
        internal static string DeviceType {
            get {
                return ResourceManager.GetString("DeviceType", resourceCulture);
            }
        }
        
        internal static string Disclaimer {
            get {
                return ResourceManager.GetString("Disclaimer", resourceCulture);
            }
        }
        
        internal static string Disconnecting {
            get {
                return ResourceManager.GetString("Disconnecting", resourceCulture);
            }
        }
        
        internal static string DurationMs {
            get {
                return ResourceManager.GetString("DurationMs", resourceCulture);
            }
        }
        
        internal static string EnterControlPointDuration {
            get {
                return ResourceManager.GetString("EnterControlPointDuration", resourceCulture);
            }
        }
        
        internal static string EnterCreationName {
            get {
                return ResourceManager.GetString("EnterCreationName", resourceCulture);
            }
        }
        
        internal static string EnterDeviceName {
            get {
                return ResourceManager.GetString("EnterDeviceName", resourceCulture);
            }
        }
        
        internal static string EnterProfileName {
            get {
                return ResourceManager.GetString("EnterProfileName", resourceCulture);
            }
        }
        
        internal static string EnterSequenceName {
            get {
                return ResourceManager.GetString("EnterSequenceName", resourceCulture);
            }
        }
        
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        internal static string ErrorDuringScanning {
            get {
                return ResourceManager.GetString("ErrorDuringScanning", resourceCulture);
            }
        }
        
        internal static string ExternalLibraries {
            get {
                return ResourceManager.GetString("ExternalLibraries", resourceCulture);
            }
        }
        
        internal static string FailedToConnect {
            get {
                return ResourceManager.GetString("FailedToConnect", resourceCulture);
            }
        }
        
        internal static string IconSet {
            get {
                return ResourceManager.GetString("IconSet", resourceCulture);
            }
        }
        
        internal static string Interpolate {
            get {
                return ResourceManager.GetString("Interpolate", resourceCulture);
            }
        }
        
        internal static string Inv {
            get {
                return ResourceManager.GetString("Inv", resourceCulture);
            }
        }
        
        internal static string Invert {
            get {
                return ResourceManager.GetString("Invert", resourceCulture);
            }
        }
        
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        internal static string LocationPermissionIsNeeded {
            get {
                return ResourceManager.GetString("LocationPermissionIsNeeded", resourceCulture);
            }
        }
        
        internal static string Loop {
            get {
                return ResourceManager.GetString("Loop", resourceCulture);
            }
        }
        
        internal static string MaxOutput {
            get {
                return ResourceManager.GetString("MaxOutput", resourceCulture);
            }
        }
        
        internal static string Missing {
            get {
                return ResourceManager.GetString("Missing", resourceCulture);
            }
        }
        
        internal static string MissingDevices {
            get {
                return ResourceManager.GetString("MissingDevices", resourceCulture);
            }
        }
        
        internal static string MissingSequence {
            get {
                return ResourceManager.GetString("MissingSequence", resourceCulture);
            }
        }
        
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        internal static string NoControllerActions {
            get {
                return ResourceManager.GetString("NoControllerActions", resourceCulture);
            }
        }
        
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        internal static string OutputLevel {
            get {
                return ResourceManager.GetString("OutputLevel", resourceCulture);
            }
        }
        
        internal static string PermissionRequest {
            get {
                return ResourceManager.GetString("PermissionRequest", resourceCulture);
            }
        }
        
        internal static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        internal static string PressButtonOrMoveJoy {
            get {
                return ResourceManager.GetString("PressButtonOrMoveJoy", resourceCulture);
            }
        }
        
        internal static string PressButtonsOrMoveJoys {
            get {
                return ResourceManager.GetString("PressButtonsOrMoveJoys", resourceCulture);
            }
        }
        
        internal static string PressScanToDiscoverDevices {
            get {
                return ResourceManager.GetString("PressScanToDiscoverDevices", resourceCulture);
            }
        }
        
        internal static string ProfileName {
            get {
                return ResourceManager.GetString("ProfileName", resourceCulture);
            }
        }
        
        internal static string ProfileNameAlreadyExists {
            get {
                return ResourceManager.GetString("ProfileNameAlreadyExists", resourceCulture);
            }
        }        
        
        internal static string ProfileNameCanNotBeEmpty {
            get {
                return ResourceManager.GetString("ProfileNameCanNotBeEmpty", resourceCulture);
            }
        }
        
        internal static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        internal static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        internal static string Renaming {
            get {
                return ResourceManager.GetString("Renaming", resourceCulture);
            }
        }
        
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        internal static string Reseting {
            get {
                return ResourceManager.GetString("Reseting", resourceCulture);
            }
        }
        
        internal static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        internal static string ScanForDevicesFirst {
            get {
                return ResourceManager.GetString("ScanForDevicesFirst", resourceCulture);
            }
        }
        
        internal static string Scanning {
            get {
                return ResourceManager.GetString("Scanning", resourceCulture);
            }
        }
        
        internal static string SearchingForDevices {
            get {
                return ResourceManager.GetString("SearchingForDevices", resourceCulture);
            }
        }
        
        internal static string SelectDevice {
            get {
                return ResourceManager.GetString("SelectDevice", resourceCulture);
            }
        }
        
        internal static string SelectDeviceBeforeSaving {
            get {
                return ResourceManager.GetString("SelectDeviceBeforeSaving", resourceCulture);
            }
        }
        
        internal static string SelectSequence {
            get {
                return ResourceManager.GetString("SelectSequence", resourceCulture);
            }
        }
        
        internal static string Sequence {
            get {
                return ResourceManager.GetString("Sequence", resourceCulture);
            }
        }
        
        internal static string SequenceName {
            get {
                return ResourceManager.GetString("SequenceName", resourceCulture);
            }
        }
        
        internal static string SequenceNameCanNotBeEmpty {
            get {
                return ResourceManager.GetString("SequenceNameCanNotBeEmpty", resourceCulture);
            }
        }
        
        internal static string SequenceNameIsUsed {
            get {
                return ResourceManager.GetString("SequenceNameIsUsed", resourceCulture);
            }
        }
        
        internal static string Sequences {
            get {
                return ResourceManager.GetString("Sequences", resourceCulture);
            }
        }
        
        internal static string ServoAngle {
            get {
                return ResourceManager.GetString("ServoAngle", resourceCulture);
            }
        }
        
        internal static string ShortChannel {
            get {
                return ResourceManager.GetString("ShortChannel", resourceCulture);
            }
        }
        
        internal static string StepperAngle {
            get {
                return ResourceManager.GetString("StepperAngle", resourceCulture);
            }
        }
        
        internal static string TurnOnBluetoothToConnect {
            get {
                return ResourceManager.GetString("TurnOnBluetoothToConnect", resourceCulture);
            }
        }
        
        internal static string TurnOnBluetoothToConnectBluetoothDevices {
            get {
                return ResourceManager.GetString("TurnOnBluetoothToConnectBluetoothDevices", resourceCulture);
            }
        }
        
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        internal static string ValueMustBeNumeric {
            get {
                return ResourceManager.GetString("ValueMustBeNumeric", resourceCulture);
            }
        }
        
        internal static string ValueOutOfRange {
            get {
                return ResourceManager.GetString("ValueOutOfRange", resourceCulture);
            }
        }
        
        internal static string ValuePercent {
            get {
                return ResourceManager.GetString("ValuePercent", resourceCulture);
            }
        }
        
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
