//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrickController2.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TranslationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TranslationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrickController2.Resources.TranslationResources", typeof(TranslationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add controller events.
        /// </summary>
        internal static string AddControllerEvents {
            get {
                return ResourceManager.GetString("AddControllerEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add controller profiles.
        /// </summary>
        internal static string AddControllerProfiles {
            get {
                return ResourceManager.GetString("AddControllerProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add control points.
        /// </summary>
        internal static string AddControlPoints {
            get {
                return ResourceManager.GetString("AddControlPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add creations.
        /// </summary>
        internal static string AddCreations {
            get {
                return ResourceManager.GetString("AddCreations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add sequences.
        /// </summary>
        internal static string AddSequences {
            get {
                return ResourceManager.GetString("AddSequences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced settings.
        /// </summary>
        internal static string AdvancedSettings {
            get {
                return ResourceManager.GetString("AdvancedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this controller action?.
        /// </summary>
        internal static string AreYouSureToDeleteControllerAction {
            get {
                return ResourceManager.GetString("AreYouSureToDeleteControllerAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete controller event.
        /// </summary>
        internal static string AreYouSureToDeleteControllerEvent {
            get {
                return ResourceManager.GetString("AreYouSureToDeleteControllerEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this control point?.
        /// </summary>
        internal static string AreYouSureToDeleteControlPoint {
            get {
                return ResourceManager.GetString("AreYouSureToDeleteControlPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete creation.
        /// </summary>
        internal static string AreYouSureToDeleteCreation {
            get {
                return ResourceManager.GetString("AreYouSureToDeleteCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete device.
        /// </summary>
        internal static string AreYouSureToDeleteDevice {
            get {
                return ResourceManager.GetString("AreYouSureToDeleteDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete profile.
        /// </summary>
        internal static string AreYouSureToDeleteProfile {
            get {
                return ResourceManager.GetString("AreYouSureToDeleteProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete sequence.
        /// </summary>
        internal static string AreYouSureToDeleteSequence {
            get {
                return ResourceManager.GetString("AreYouSureToDeleteSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this controller action?.
        /// </summary>
        internal static string AreYouSureToDeleteThisControllerAcrion {
            get {
                return ResourceManager.GetString("AreYouSureToDeleteThisControllerAcrion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto calibrate.
        /// </summary>
        internal static string AutoCalibrate {
            get {
                return ResourceManager.GetString("AutoCalibrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joy active zone.
        /// </summary>
        internal static string AxisActiveZone {
            get {
                return ResourceManager.GetString("AxisActiveZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joy characteristic.
        /// </summary>
        internal static string AxisCharacteristic {
            get {
                return ResourceManager.GetString("AxisCharacteristic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joy dead zone.
        /// </summary>
        internal static string AxisDeadZone {
            get {
                return ResourceManager.GetString("AxisDeadZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joy type.
        /// </summary>
        internal static string AxisType {
            get {
                return ResourceManager.GetString("AxisType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base angle.
        /// </summary>
        internal static string BaseAngle {
            get {
                return ResourceManager.GetString("BaseAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery.
        /// </summary>
        internal static string Battery {
            get {
                return ResourceManager.GetString("Battery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        internal static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluetooth devices will NOT be available.
        /// </summary>
        internal static string BluetoothDevicesWillNOTBeAvailable {
            get {
                return ResourceManager.GetString("BluetoothDevicesWillNOTBeAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluetooth is turned off..
        /// </summary>
        internal static string BluetoothIsTurnedOff {
            get {
                return ResourceManager.GetString("BluetoothIsTurnedOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button type.
        /// </summary>
        internal static string ButtonType {
            get {
                return ResourceManager.GetString("ButtonType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuWizz 2 output level.
        /// </summary>
        internal static string BuWizz2OutputLevel {
            get {
                return ResourceManager.GetString("BuWizz2OutputLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuWizz output level.
        /// </summary>
        internal static string BuWizzOutputLevel {
            get {
                return ResourceManager.GetString("BuWizzOutputLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibrating....
        /// </summary>
        internal static string Calibrating {
            get {
                return ResourceManager.GetString("Calibrating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel setup.
        /// </summary>
        internal static string ChannelSetup {
            get {
                return ResourceManager.GetString("ChannelSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel type.
        /// </summary>
        internal static string ChannelType {
            get {
                return ResourceManager.GetString("ChannelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting.
        /// </summary>
        internal static string Connecting {
            get {
                return ResourceManager.GetString("Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to: .
        /// </summary>
        internal static string ConnectingTo {
            get {
                return ResourceManager.GetString("ConnectingTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller.
        /// </summary>
        internal static string Controller {
            get {
                return ResourceManager.GetString("Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller Action.
        /// </summary>
        internal static string ControllerAction {
            get {
                return ResourceManager.GetString("ControllerAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller profile.
        /// </summary>
        internal static string ControllerProfile {
            get {
                return ResourceManager.GetString("ControllerProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller tester.
        /// </summary>
        internal static string ControllerTester {
            get {
                return ResourceManager.GetString("ControllerTester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control point.
        /// </summary>
        internal static string ControlPoint {
            get {
                return ResourceManager.GetString("ControlPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating....
        /// </summary>
        internal static string Creating {
            get {
                return ResourceManager.GetString("Creating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation.
        /// </summary>
        internal static string Creation {
            get {
                return ResourceManager.GetString("Creation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation name.
        /// </summary>
        internal static string CreationName {
            get {
                return ResourceManager.GetString("CreationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation name can not be empty.
        /// </summary>
        internal static string CreationNameCanNotBeEmpty {
            get {
                return ResourceManager.GetString("CreationNameCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creations.
        /// </summary>
        internal static string Creations {
            get {
                return ResourceManager.GetString("Creations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default profile.
        /// </summary>
        internal static string DefaultProfile {
            get {
                return ResourceManager.GetString("DefaultProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting....
        /// </summary>
        internal static string Deleting {
            get {
                return ResourceManager.GetString("Deleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        internal static string Device {
            get {
                return ResourceManager.GetString("Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device name.
        /// </summary>
        internal static string DeviceName {
            get {
                return ResourceManager.GetString("DeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device name can not be empty..
        /// </summary>
        internal static string DeviceNameCanNotBeEmpty {
            get {
                return ResourceManager.GetString("DeviceNameCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        internal static string Devices {
            get {
                return ResourceManager.GetString("Devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device type.
        /// </summary>
        internal static string DeviceType {
            get {
                return ResourceManager.GetString("DeviceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disclaimer.
        /// </summary>
        internal static string Disclaimer {
            get {
                return ResourceManager.GetString("Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnecting.
        /// </summary>
        internal static string Disconnecting {
            get {
                return ResourceManager.GetString("Disconnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to overwrite it?.
        /// </summary>
        internal static string DoYouWantToOverWrite {
            get {
                return ResourceManager.GetString("DoYouWantToOverWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration (ms).
        /// </summary>
        internal static string DurationMs {
            get {
                return ResourceManager.GetString("DurationMs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the control point duration between 300 and 10000 ms..
        /// </summary>
        internal static string EnterControlPointDuration {
            get {
                return ResourceManager.GetString("EnterControlPointDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a creation name.
        /// </summary>
        internal static string EnterCreationName {
            get {
                return ResourceManager.GetString("EnterCreationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a device name.
        /// </summary>
        internal static string EnterDeviceName {
            get {
                return ResourceManager.GetString("EnterDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a new profile name.
        /// </summary>
        internal static string EnterProfileName {
            get {
                return ResourceManager.GetString("EnterProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a sequence name.
        /// </summary>
        internal static string EnterSequenceName {
            get {
                return ResourceManager.GetString("EnterSequenceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during scanning.
        /// </summary>
        internal static string ErrorDuringScanning {
            get {
                return ResourceManager.GetString("ErrorDuringScanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export successful:.
        /// </summary>
        internal static string ExportSuccessful {
            get {
                return ResourceManager.GetString("ExportSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3rd party components.
        /// </summary>
        internal static string ExternalLibraries {
            get {
                return ResourceManager.GetString("ExternalLibraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect..
        /// </summary>
        internal static string FailedToConnect {
            get {
                return ResourceManager.GetString("FailedToConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to export the controller profile..
        /// </summary>
        internal static string FailedToExportControllerProfile {
            get {
                return ResourceManager.GetString("FailedToExportControllerProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to export the creation..
        /// </summary>
        internal static string FailedToExportCreation {
            get {
                return ResourceManager.GetString("FailedToExportCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to export the sequence..
        /// </summary>
        internal static string FailedToExportSequence {
            get {
                return ResourceManager.GetString("FailedToExportSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to import the controller profile..
        /// </summary>
        internal static string FailedToImportControllerProfile {
            get {
                return ResourceManager.GetString("FailedToImportControllerProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to import the creation..
        /// </summary>
        internal static string FailedToImportCreation {
            get {
                return ResourceManager.GetString("FailedToImportCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to import the sequence..
        /// </summary>
        internal static string FailedToImportSequence {
            get {
                return ResourceManager.GetString("FailedToImportSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File already exits.
        /// </summary>
        internal static string FileAlreadyExists {
            get {
                return ResourceManager.GetString("FileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon set.
        /// </summary>
        internal static string IconSet {
            get {
                return ResourceManager.GetString("IconSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpolate.
        /// </summary>
        internal static string Interpolate {
            get {
                return ResourceManager.GetString("Interpolate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inv.
        /// </summary>
        internal static string Inv {
            get {
                return ResourceManager.GetString("Inv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert.
        /// </summary>
        internal static string Invert {
            get {
                return ResourceManager.GetString("Invert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location permission is needed for accessing bluetooth.
        /// </summary>
        internal static string LocationPermissionIsNeeded {
            get {
                return ResourceManager.GetString("LocationPermissionIsNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop.
        /// </summary>
        internal static string Loop {
            get {
                return ResourceManager.GetString("Loop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max output.
        /// </summary>
        internal static string MaxOutput {
            get {
                return ResourceManager.GetString("MaxOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing.
        /// </summary>
        internal static string Missing {
            get {
                return ResourceManager.GetString("Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are missing devices in the creation setup..
        /// </summary>
        internal static string MissingDevices {
            get {
                return ResourceManager.GetString("MissingDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing sequence.
        /// </summary>
        internal static string MissingSequence {
            get {
                return ResourceManager.GetString("MissingSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no controller actions added to the creation..
        /// </summary>
        internal static string NoControllerActions {
            get {
                return ResourceManager.GetString("NoControllerActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No creations to import..
        /// </summary>
        internal static string NoCreationsToImport {
            get {
                return ResourceManager.GetString("NoCreationsToImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No controller profiles to import..
        /// </summary>
        internal static string NoProfilesToImport {
            get {
                return ResourceManager.GetString("NoProfilesToImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no sequences..
        /// </summary>
        internal static string NoSequences {
            get {
                return ResourceManager.GetString("NoSequences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No sequences to import..
        /// </summary>
        internal static string NoSequencesToImport {
            get {
                return ResourceManager.GetString("NoSequencesToImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output level.
        /// </summary>
        internal static string OutputLevel {
            get {
                return ResourceManager.GetString("OutputLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission request.
        /// </summary>
        internal static string PermissionRequest {
            get {
                return ResourceManager.GetString("PermissionRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press a button or move a joy on the game controller.
        /// </summary>
        internal static string PressButtonOrMoveJoy {
            get {
                return ResourceManager.GetString("PressButtonOrMoveJoy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press buttons or move joys.
        /// </summary>
        internal static string PressButtonsOrMoveJoys {
            get {
                return ResourceManager.GetString("PressButtonsOrMoveJoys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press scan to discover devices.
        /// </summary>
        internal static string PressScanToDiscoverDevices {
            get {
                return ResourceManager.GetString("PressScanToDiscoverDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading and saving profiles will not be available..
        /// </summary>
        internal static string ProfileLoadSaveWillNotBeAvailable {
            get {
                return ResourceManager.GetString("ProfileLoadSaveWillNotBeAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile name.
        /// </summary>
        internal static string ProfileName {
            get {
                return ResourceManager.GetString("ProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile name can not be empty..
        /// </summary>
        internal static string ProfileNameCanNotBeEmpty {
            get {
                return ResourceManager.GetString("ProfileNameCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        internal static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renaming....
        /// </summary>
        internal static string Renaming {
            get {
                return ResourceManager.GetString("Renaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reseting....
        /// </summary>
        internal static string Reseting {
            get {
                return ResourceManager.GetString("Reseting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving....
        /// </summary>
        internal static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan for devices before adding controller events!.
        /// </summary>
        internal static string ScanForDevicesFirst {
            get {
                return ResourceManager.GetString("ScanForDevicesFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning....
        /// </summary>
        internal static string Scanning {
            get {
                return ResourceManager.GetString("Scanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for devices..
        /// </summary>
        internal static string SearchingForDevices {
            get {
                return ResourceManager.GetString("SearchingForDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select device.
        /// </summary>
        internal static string SelectDevice {
            get {
                return ResourceManager.GetString("SelectDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a device before saving..
        /// </summary>
        internal static string SelectDeviceBeforeSaving {
            get {
                return ResourceManager.GetString("SelectDeviceBeforeSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a sequence.
        /// </summary>
        internal static string SelectSequence {
            get {
                return ResourceManager.GetString("SelectSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence.
        /// </summary>
        internal static string Sequence {
            get {
                return ResourceManager.GetString("Sequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence name.
        /// </summary>
        internal static string SequenceName {
            get {
                return ResourceManager.GetString("SequenceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence name can not be empty.
        /// </summary>
        internal static string SequenceNameCanNotBeEmpty {
            get {
                return ResourceManager.GetString("SequenceNameCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sequence name is already used.
        /// </summary>
        internal static string SequenceNameIsUsed {
            get {
                return ResourceManager.GetString("SequenceNameIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequences.
        /// </summary>
        internal static string Sequences {
            get {
                return ResourceManager.GetString("Sequences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servo range.
        /// </summary>
        internal static string ServoAngle {
            get {
                return ResourceManager.GetString("ServoAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ch.
        /// </summary>
        internal static string ShortChannel {
            get {
                return ResourceManager.GetString("ShortChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stepper angle.
        /// </summary>
        internal static string StepperAngle {
            get {
                return ResourceManager.GetString("StepperAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn bluetooth on to connect to a bluetooth device..
        /// </summary>
        internal static string TurnOnBluetoothToConnect {
            get {
                return ResourceManager.GetString("TurnOnBluetoothToConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn bluetooth on to connect to bluetooth device(s)..
        /// </summary>
        internal static string TurnOnBluetoothToConnectBluetoothDevices {
            get {
                return ResourceManager.GetString("TurnOnBluetoothToConnectBluetoothDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be numeric..
        /// </summary>
        internal static string ValueMustBeNumeric {
            get {
                return ResourceManager.GetString("ValueMustBeNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value out of range..
        /// </summary>
        internal static string ValueOutOfRange {
            get {
                return ResourceManager.GetString("ValueOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value (%).
        /// </summary>
        internal static string ValuePercent {
            get {
                return ResourceManager.GetString("ValuePercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
